database:
  needed: false
  type: "mysql"
  filename: "XCore.db"
  host: "127.0.0.1"
  port: "3306"
  database: "database"
  username: "username"
  password: "password"
redis:
  needed: false
  host: "127.0.0.1"
  port: "6379"
  database: 0
  password: "password"
memoryfixer:
  needed: false
  min: 1024
chat:
  needed: false
  announce_vip_join: false
injector:
  enabled: true